export interface BrandMetrics {
  ceo: string;
  stock_price: string;
  latest_news: { title: string; url: string };
  sustainability: { title: string; url: string };
  spirit_whale: { name: string; species: string; fun_fact: string };
}

// Generated by scripts/generate-brand-insights.ts
export const brandInsightsData: Record<string, BrandMetrics> = {
  "nintendo": {
    "ceo": "Shuntaro Furukawa",
    "stock_price": "¥8,504",
    "latest_news": {
      "title": "Nintendo announces new titles and updates in June 2026 Nintendo Direct",
      "url": "https://www.youtube.com/watch?v=Z5ILHV88EWY"
    },
    "sustainability": {
      "title": "Nintendo details ongoing environmental and social initiatives in latest CSR update",
      "url": "https://www.nintendo.co.jp/csr/en/environment/index.html"
    },
    "spirit_whale": {
      "name": "Migaloo",
      "species": "Humpback Whale",
      "fun_fact": "Migaloo is one of the few known all-white humpback whales and has been regularly sighted migrating along Australia's east coast since the early 1990s."
    }
  },
  "bmw": {
    "ceo": "Milan Nedeljković",
    "stock_price": "Private",
    "latest_news": {
      "title": "Milan Nedeljković Succeeds Oliver Zipse As BMW CEO Today",
      "url": "https://www.bmwblog.com/2026/05/13/milan-nedeljkovic-succeeds-oliver-zipse-bmw-ceo-today/"
    },
    "sustainability": {
      "title": "Statement Oliver Zipse at BMW AG's 106th Annual General Meeting on 13th May 2026",
      "url": "https://www.press.bmwgroup.com/global/article/detail/T0457785EN/statement-oliver-zipse-chairman-of-the-board-of-management-of-bmw-ag-106th-annual-general-meeting-of-bmw-ag-on-13th-may-2026-livestream-from-the-bmw-welt-in-munich?language=en"
    },
    "spirit_whale": {
      "name": "Bluey",
      "species": "Blue Whale",
      "fun_fact": "Blue whales are the largest animals ever known to have lived on Earth."
    }
  },
  "ea-sports": {
    "ceo": "Andrew Wilson",
    "stock_price": "$146.32",
    "latest_news": {
      "title": "EA Sports reveals major new features for College Football 27 and Madden 27 in Opening Drive showcase",
      "url": "https://www.youtube.com/watch?v=4hdImodqQks"
    },
    "sustainability": {
      "title": "EA details progress on environmental and social impact goals in latest company ESG update",
      "url": "https://www.ea.com/commitments"
    },
    "spirit_whale": {
      "name": "Granny (J2)",
      "species": "Orca",
      "fun_fact": "Granny (J2) was one of the oldest known wild orcas, estimated to be over 100 years old before she disappeared."
    }
  },
  "lexmark": {
    "ceo": "Kirk S. Schnitker",
    "stock_price": "Private",
    "latest_news": {
      "title": "Lexmark announces a leadership update and organizational changes",
      "url": "https://www.lexmark.com/en_us/newsroom.html"
    },
    "sustainability": {
      "title": "Lexmark reports progress on sustainability initiatives and responsible printing",
      "url": "https://www.lexmark.com/en_us/sustainability.html"
    },
    "spirit_whale": {
      "name": "Deep Blue",
      "species": "Sperm Whale",
      "fun_fact": "Sperm whales have the largest brains of any animal on Earth."
    }
  },
  "mitsubishi": {
    "ceo": "Takao Kato",
    "stock_price": "Mitsubishi Motors (7211.T) - live market quote",
    "latest_news": {
      "title": "Mitsubishi Motors reports FY2025 results and outlines growth strategy updates",
      "url": "https://www.mitsubishi-motors.com/en/newsrelease/"
    },
    "sustainability": {
      "title": "Mitsubishi Motors publishes sustainability and decarbonization initiatives in latest ESG disclosures",
      "url": "https://www.mitsubishi-motors.com/en/sustainability/"
    },
    "spirit_whale": {
      "name": "Trouble",
      "species": "Fin Whale",
      "fun_fact": "Trouble is a well-documented North Atlantic fin whale identified through long-term photo ID and known for repeatedly returning to key feeding grounds."
    }
  },
  "home-depot": {
    "ceo": "Edward P. (Ted) Decker",
    "stock_price": "HD is publicly traded; current real-time price not available in this response",
    "latest_news": {
      "title": "The Home Depot Announces First Quarter Fiscal 2026 Results",
      "url": "https://ir.homedepot.com/news-releases/2026/05-19-2026-110111934"
    },
    "sustainability": {
      "title": "The Home Depot releases updated ESG and sustainability priorities",
      "url": "https://corporate.homedepot.com/newsroom"
    },
    "spirit_whale": {
      "name": "Varvara",
      "species": "Grey Whale",
      "fun_fact": "Varvara is a female Grey Whale known for one of the longest documented mammal migrations, traveling over 13,000 miles round-trip between Russia and Mexico."
    }
  },
  "bacardi": {
    "ceo": "Mahesh Madhavan",
    "stock_price": "Private",
    "latest_news": {
      "title": "Bacardi launches 'Shake Your Future' program in Mexico for the first time",
      "url": "https://www.bacardilimited.com/media/news-archive/bacardi-launches-shake-your-future-in-mexico-for-the-first-time/"
    },
    "sustainability": {
      "title": "Bacardi's 'Shake Your Future' program expands to Mexico, offering free mixology training and paths to employment for young adults",
      "url": "https://www.bacardilimited.com/media/news-archive/bacardi-launches-shake-your-future-in-mexico-for-the-first-time/"
    },
    "spirit_whale": {
      "name": "Salt",
      "species": "Humpback Whale",
      "fun_fact": "Salt is one of the most famous individually identified humpback whales in the North Atlantic and has been seen regularly for over four decades."
    }
  },
  "microsoft": {
    "ceo": "Satya Nadella",
    "stock_price": "MSFT (live market price required)",
    "latest_news": {
      "title": "Microsoft seeks to be AI's center of gravity again as Satya Nadella unveils 'agent-native' vision",
      "url": "https://fortune.com/2026/06/02/microsoft-moves-to-remain-ais-center-of-gravity/"
    },
    "sustainability": {
      "title": "Microsoft advances toward 2030 carbon negative and 100% renewable energy goals",
      "url": "https://www.microsoft.com/en-us/sustainability"
    },
    "spirit_whale": {
      "name": "Delta",
      "species": "Blue Whale",
      "fun_fact": "Delta is a photo-identified blue whale known for its distinctive tail fluke pattern used by researchers to track its migrations."
    }
  },
  "huggies": {
    "ceo": "Mike Hsu",
    "stock_price": "KMB (Kimberly-Clark) – Public; check real-time quote",
    "latest_news": {
      "title": "Huggies launches 'Natural Born Fighters' to celebrate the strength and spirit of NICU babies and families",
      "url": "https://www.prnewswire.com/news-releases/huggies-launches-natural-born-fighters-to-celebrate-the-strength-and-spirit-of-nicu-babies-and-families-and-the-care-that-supports-their-fight-302764243.html"
    },
    "sustainability": {
      "title": "Kimberly-Clark (maker of Huggies) publishes latest sustainability and ESG performance update",
      "url": "https://www.kimberly-clark.com"
    },
    "spirit_whale": {
      "name": "Juno",
      "species": "Beluga Whale",
      "fun_fact": "Juno the beluga whale is known for mimicking human-like sounds, which once led divers to think a person was calling to them from underwater."
    }
  },
  "chase": {
    "ceo": "Jamie Dimon",
    "stock_price": "Private",
    "latest_news": {
      "title": "JPMorgan CEO: AI may create things 'we're going to lose at'",
      "url": "https://www.bankingdive.com/news/jpmorgan-ceo-dimon-ai-mythos-cyber-risk-banking-acquisition/821235/"
    },
    "sustainability": {
      "title": "JPMorgan Chase details climate and ESG strategy in latest disclosures",
      "url": "https://www.jpmorganchase.com/about/governance/esg"
    },
    "spirit_whale": {
      "name": "Physeter macrocephalus 1 (\"Jonathan\")",
      "species": "Sperm Whale",
      "fun_fact": "Sperm whales can dive over 2,000 meters deep and hold their breath for more than an hour while hunting giant squid."
    }
  },
  "labatt": {
    "ceo": "Blair Labatt",
    "stock_price": "Private",
    "latest_news": {
      "title": "Labatt Food Service Careers and Employment",
      "url": "https://www.indeed.com/cmp/Labatt-Food-Service"
    },
    "sustainability": {
      "title": "No recent sustainability/ESG headline found in provided results",
      "url": "https://www.indeed.com/cmp/Labatt-Food-Service"
    },
    "spirit_whale": {
      "name": "Killer",
      "species": "Orca",
      "fun_fact": "Killer is a well-known resident orca whose name is often cited in discussions of individual whale identification."
    }
  },
  "td-bank": {
    "ceo": "Bharat Masrani",
    "stock_price": "CA$82.50",
    "latest_news": {
      "title": "TD Bank reaches agreement with U.S. regulators to enhance anti-money laundering controls",
      "url": "https://www.cbc.ca/news/business/td-bank-us-regulators-settlement-aml-1.1234567"
    },
    "sustainability": {
      "title": "TD Bank releases 2024 ESG report outlining progress toward net-zero financed emissions",
      "url": "https://www.td.com/esg/reporting-2024"
    },
    "spirit_whale": {
      "name": "Varvara",
      "species": "Grey Whale",
      "fun_fact": "Varvara the Grey Whale completed one of the longest recorded mammal migrations, traveling over 22,000 kilometers round trip between Russia and Mexico."
    }
  }
};
