/*
client must be 1 one word for some reason?!
*/

const identity = {
  name: "headwinds",
  link: "https://www.headwinds.net",
  slogan: "",
  works: {
    name: "works",
    link: "https://www.headwinds.net/works",
  },
  about: {
    name: "about",
    link: "https://www.headwinds.net/about",
  },
  contact: {
    name: "contact",
    link: "https://www.headwinds.net/contact",
  },
  projects: [
    {
      name: "Validere",
      description:
        "Validere is a measurement and reporting company for carbon emissions. I worked on three main sections of their reporting app: the dashboard featuring charting components, key metrics, a data visualisation clustering thousands of facilities; forms with conditionally rendered fields; and workflows with branching task management. I also spearheaded the release of their first React Native application.",
      client: "Energy",
      company: "Validere",
      tags: "security,file sharing, messaging",
      vertical: "Energy",
      duration: 25,
      team: 1,
      role: "Senior Fullstack Developer",
      tech: "React, MapBox, Node",
      year: 2018,
      localized: false,
      locked: false,
      route: "/validere",
      id: 1,
    },
    /*
    {
      name: 'TodaQ Financial',
      description:
        'Frontend Developer,UI Design & Data Visualization',
      client: 'TodaQ',
      company: 'TodaQ',
      tags: 'security,file sharing, messaging',
      vertical: "Financial",
      duration: 25,
      team: 1,
      role: 'Lead UI',
      tech: 'ClojureScript',
      year: 2018,
      localized: false,
      locked: false,
      route: "/toda",
      id: 2
    },
    {
      name: 'Brandon Flowers',
      description:
        'Frontend Developer,UI Design & Data Visualization',
      client: 'Headwinds',
      company: 'QoC Health',
      tags: 'security,file sharing, messaging',
      vertical: "Brandon Flowers",
      duration: 25,
      team: 1,
      role: 'Lead UI',
      tech: 'React 16 & Redux',
      year: 2003,
      localized: false,
      locked: false,
      route: "/bio",
      id: 3
    },
    {
      name: 'Patient Network',
      description:
        'The Trioova Patient Network enables patients to connect with care-givers and other providers. Patients can form their own connected care circle and engage in private or team chat. They can also upload and share files as well as search a marketplace to connect with providers across the country',
      client: 'Trioova',
      company: 'QoC',
      tags: 'security,file sharing, messaging',
      vertical: "Health",
      duration: 4,
      team: 4,
      role: 'Lead UI',
      tech: 'React 16 & Redux',
      year: 2018,
      localized: false,
      locked: false,
      route: "/trioova",
      id: 4
    },
    */
    {
      name: "Shoppers Drug Mart",
      description:
        "Loblaw Companies Limited is one of the most successful and largest corporations in Canada. As part of the Shoppers Drug Mart team, I’ve helped build and maintain their eCommerce platform with React, GraphQL, and Go. I lead a small team of developers, writing frontend components, test automation with Playwright, and responsive UI from landing page to checkout, ensuring both the desktop and mobile experience was efficient and delighted the customers.",
      client: "Shoppers Drug Mart",
      company: "Loblaw Companies Limited",
      tags: "security,file sharing, messaging",
      vertical: "Health",
      duration: 4,
      team: 4,
      role: "Lead UI",
      tech: "React, Redux, Go, Postgres, GraphQL",
      year: 2020,
      localized: false,
      locked: false,
      route: "/shoppers-drug-mart",
      id: 4,
    },
    {
      name: "Thought Spot",
      description:
        "Thought Spot is a responsive (desktop & mobile) web app for CAMH. It talks to both the Google Places and Mapbox APIs as well as performs full text and geolocation proximity search through the HIPAA-compliant QoC API.",
      client: "CAMH",
      company: "QoC Health",
      tags: "security,experience,game,world",
      vertical: "Health",
      duration: 4,
      team: 4,
      role: "Frontend",
      localized: false,
      tech: "React, Java",
      year: 2017,
      locked: false,
      route: "/camh",
      id: 5,
    },
    {
      name: "Voice of the Customer",
      description:
        "Agents were required to manually tag thousands of lines of chat data. Natural Language Processing and Machine Learning alorigthms can now automatically tag the vast majority of this text reducing human involment down to much more manageable results. Inspired by an excel-like interface that talks to ML services, this tool allows an agent to quickly review problematic tags and reduced the time it takes to develop a model for the Data Science team down from 3 months to 1 week.",
      client: "247",
      company: "247 AI",
      vertical: "Customer Service",
      tags: "security,experience,game,world",
      duration: 4,
      team: 4,
      role: "Fullstack",
      tech: "React, D3, Java",
      year: 2016,
      localized: true,
      locked: false,
      route: "/247",
      id: 6,
    },
    {
      name: "Predictive Suggestions",
      description:
        "A chatbot component which provides up to 3 quick answers from a machine learning service that update as the user types.",
      client: "Ada",
      company: "Ada Support247 ai",
      vertical: "Customer Service",
      tags: "security,conversation,ML,NLP",
      duration: 4,
      team: 4,
      role: "Frontend",
      tech: "React/Redux",
      year: 2019,
      localized: true,
      locked: false,
      route: "/ada",
      id: 65,
    },
    {
      name: "Total Drama Avatar Builder",
      description:
        "Inspired by a monster maker, kids can use this tool to build their own total drama avatar by selecting a head, body, feet, and background, and then share them with their friends.",
      client: "Corus",
      company: "Zincroe",
      tags: "security,experience,game,world",
      duration: 4,
      vertical: "Entertainment",
      team: 4,
      role: "UI",
      tech: "Flash AS3",
      localized: false,
      year: 2010,
      locked: false,
      route: "/totaldrama",
      id: 7,
    },
    {
      name: "Lancer Earth",
      description:
        "An around the world tour featuring the Mitsubishi Lancer. This experience site won my first and only FWA award and showcased incredible 3D video from one of artists behind the movie The Matrix",
      client: "Mitsubishi",
      tags: "security,experience,game,world",
      duration: 4,
      team: 4,
      role: "UI",
      tech: "Flash AS3",
      vertical: "Automotive",
      localized: true,
      year: 2007,
      locked: false,
      route: "/mitsubishi",
      id: 8,
    },
    {
      name: "World Tour",
      description:
        "In order to promote version 2 of the MSN search toolbar, we developed a global guiz contest that would be played out in real-time over the course of 4 weeks and may involve as many as 12 million users. I helped the team of designers and developers assemble the game assests, and developed the game logic that relies on Flash/XML communication with ASP.NET. We also did some sha-256 encryption to protect our users, and produced two versions in French and English.",
      client: "Microsoft",
      tags: "security,experience,game,world",
      duration: 4,
      team: 4,
      role: "UI",
      tech: "Flash AS2",
      vertical: "Entertainment",
      localized: true,
      year: 2005,
      locked: false,
      route: "/microsoft",
      id: 9,
    },
    {
      name: "BMW Car Configurator",
      description:
        "Being able to pick and choose parts of your new beamer and the have car instantly change to reflect to your personal style is a compelling experience. Once the car is set to your liking, the configuration will be sent to a database to find appropriate dealer if the car exists or a manufacturer if he needs to be built.",
      client: "BMW",
      company: "Blast Radius",
      tags: "experience,automotive,configuration",
      duration: 4,
      vertical: "Automotive",
      team: 4,
      role: "UI",
      tech: "BackboneJS",
      api: "None",
      year: 2017,
      locked: false,
      route: "/bmw",
      id: 10,
    },
    {
      name: "Bacardi 360 Video",
      description:
        "This after party experience invites the viewer into a massive manhattan apartment. From a first person prespective, the user can scroll around in full 360 video and look anywhere in the room. As they explore, they will discover mini games and novelty items that pulls content from their Facebook profile and feed.",
      client: "Bacardi",
      tags: "experience",
      duration: 4,
      team: 4,
      role: "UI",
      tech: "Flash As3",
      vertical: "Lifestyle",
      api: "Facebook",
      year: 2013,
      locked: false,
      route: "/bacardi",
      id: 11,
    },
    {
      name: "Wii Fitness",
      description:
        "Wii Fitness combined a console game with a physical device. We built an instructional video-based website to teach players a series of excercises and then track their progress.",
      client: "Nintendo",
      company: "Blast Radius",
      tags: "experience",
      duration: 4,
      team: 4,
      role: "Fullstack",
      vertical: "Entertainment",
      tech: "Flash",
      api: "None",
      year: 2010,
      locked: false,
      route: "/nintendo",
      id: 12,
    },
    {
      name: "Labatt Wolf Pack",
      description:
        "I designed and developer a loyalty program app for Labatt to monitor beer drinkers and reward them with events and special prizes",
      client: "Labatt",
      tags: "security,experience,game,world",
      duration: 4,
      vertical: "Lifestyle",
      team: 4,
      role: "UI",
      tech: "Flash AS2",
      year: 2006,
      locked: false,
      route: "/labatt",
      id: 13,
    },
    {
      name: "The Home Depot Interactive Tools",
      description:
        "Built interactive tools for The Home Depot digital experience, helping customers explore products and plan projects online.",
      client: "The Home Depot",
      company: "Blast Radius",
      tags: "experience,retail,interactive",
      duration: 4,
      vertical: "Retail",
      team: 4,
      role: "UI",
      tech: "JavaScript",
      api: "None",
      year: 2008,
      locked: false,
      route: "/home-depot",
      id: 14,
    },
    {
      name: "Lexmark Enterprise Platform",
      description:
        "Developed enterprise web applications for Lexmark printing and imaging solutions, with a focus on front-end UI and interaction patterns.",
      client: "Lexmark",
      company: "Blast Radius",
      tags: "enterprise,experience,ui",
      duration: 4,
      vertical: "Enterprise",
      team: 4,
      role: "UI",
      tech: "JavaScript",
      api: "None",
      year: 2008,
      locked: false,
      route: "/lexmark",
      id: 15,
    },
    {
      name: "EA Sports Promotions",
      description:
        "Built interactive promotional experiences for EA Sports titles, delivering front-end UI and animation-heavy campaign work.",
      client: "EA Sports",
      company: "Blast Radius",
      tags: "experience,entertainment,gaming",
      duration: 4,
      vertical: "Entertainment",
      team: 4,
      role: "UI",
      tech: "Flash AS3",
      api: "None",
      year: 2009,
      locked: false,
      route: "/ea-sports",
      id: 16,
    },
    {
      name: "Chase Digital Banking Tools",
      description:
        "Developed interactive financial tools and promotional web experiences for Chase Manhattan digital banking.",
      client: "Chase Manhattan",
      company: "Blast Radius",
      tags: "finance,experience,interactive",
      duration: 4,
      vertical: "Financial",
      team: 4,
      role: "UI",
      tech: "Flash AS2",
      api: "None",
      year: 2007,
      locked: false,
      route: "/chase",
      id: 17,
    },
    {
      name: "Huggies Parent-Focused Experiences",
      description:
        "Created interactive campaign experiences for Huggies, focused on engaging new parents through digital content and storytelling.",
      client: "Huggies",
      company: "Blast Radius",
      tags: "experience,lifestyle,campaign",
      duration: 4,
      vertical: "Lifestyle",
      team: 4,
      role: "UI",
      tech: "Flash AS2",
      api: "None",
      year: 2008,
      locked: false,
      route: "/huggies",
      id: 18,
    },
    {
      name: "TD Bank Online Promotions",
      description:
        "Built interactive digital banking tools and promotional experiences for TD Bank online initiatives.",
      client: "TD Bank",
      company: "Blast Radius",
      tags: "finance,experience,interactive",
      duration: 4,
      vertical: "Financial",
      team: 4,
      role: "UI",
      tech: "JavaScript",
      api: "None",
      year: 2009,
      locked: false,
      route: "/td-bank",
      id: 19,
    },
  ],
};

export default identity;
