# playwright.yml
name: Run Playwright Tests

on:
  repository_dispatch:
    types: [trigger-playwright]
  pull_request:
    branches: [main, master]
    paths-ignore:
      - "**/*"

jobs:
  test:
    if: github.event_name == 'repository_dispatch' || github.event.pull_request.head.repo.default_branch == github.event.pull_request.base.repo.default_branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test --config=playwright.config.js
        env:
          PLAYWRIGHT_TEST_BASE_URL: ${{ github.event.client_payload.stagingUrl }}
